version: 2.1

base_image: &base_image hashicorp/terraform:0.12.29

working_directory: &working_directory ~/infra

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory
  environment:
    ENV: dev

persist: &persist
  run:
    name: persist
    command: |
      touch test.txt

install_dependencies: &install_dependencies
  run:
    name: install_dependencies
    command: |
      apk add make
      apk add curl

jobs:
  build:
    <<: *default_config
    steps:
      - *install_dependencies
      - *persist
      - persist_to_workspace:
          root: *working_directory
          paths:
            - test.txt
  ls:
    <<: *default_config
    steps:
      - attach_workspace:
          at: *working_directory
      - run: pwd
      - run: ls -al
workflows:
  version: 2
  test:
    jobs:
      - build
      - ls:
          requires:
            - build
