version: 2.1

commands: # a reusable command with parameters
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"

base_image: &base_image hashicorp/terraform:0.12.29

default_config: &default_config
  docker:
    - image: *base_image

persist: &persist
  run:
    name: persist
    command: |
      touch test.txt
      touch test1.txt

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - greeting:
        to: "My-Name"
  build:
    <<: *default_config
    steps:
      - *persist
      - persist_to_workspace:
          root: << pipeline.parameters.workingdir >>
          paths:
            - test.txt
            - test1.txt

  ls:
    <<: *default_config
    steps:
      - attach_workspace:
          at: << pipeline.parameters.workingdir >>
      - run: pwd
      - run: echo "$(pwd) == << pipeline.parameters.workingdir >>"

workflows:
  my-workflow:
    jobs:
      - build
      - ls:
          requires:
            - build
