version: 2.1

parameters:
  workingdir:
    type: string
    default: "~/infra/dev"

commands:
  greeting:
    parameters:
      env:
        type: string
        default: "dev"
    steps:
      - run: "export ENV=<<parameters.env>>"
      - run: echo <<parameters.env>>

base_image: &base_image hashicorp/terraform:0.12.29

default_config: &default_config
  docker:
    - image: *base_image

persist: &persist
  run:
    name: persist
    command: |
      touch test.txt
      touch test1.txt

jobs:
  build:
    <<: *default_config
    working_directory: << pipeline.parameters.workingdir >>
    steps:
      - *persist
      - persist_to_workspace:
          root: << pipeline.parameters.workingdir >>
          paths:
            - test.txt
            - test1.txt

  ls:
    <<: *default_config
    steps:
      - greeting:
        env: "My-Name"
      - attach_workspace:
          at: << pipeline.parameters.workingdir >>
      - run: pwd
      - run: echo "$(pwd) == << pipeline.parameters.workingdir >>"
      - run: env

workflows:
  my-workflow:
    jobs:
      - build
      - ls:
          requires:
            - build
