version: 2.1

executors:
  default-executor:
    docker:
      - image: hashicorp/terraform:0.12.29

parameters:
  workingdir:
    type: string
    default: "~/infra/"

commands:
  print:
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>
  greeting:
    parameters:
      env:
        type: string
        default: "dev"
    steps:
      - run: export ENV=<< parameters.env >>

jobs:
  build:
    executor: default-executor
    working_directory: ~/<< pipeline.parameters.workingdir >>/<< parameters.env >>
    parameters:
      env:
        type: string
        default: dev
    environment:
      ENV: << parameters.env >>
    steps:
      - run: echo $ENV
      - run: touch test
      - run: ls
      - run: pwd
      - persist_to_workspace:
          root: ~/<< pipeline.parameters.workingdir >>/<< parameters.env >>
          paths:
            - test
  deploy:
    executor: default-executor
    parameters:
      env:
        type: string
        default: dev
    environment:
      ENV: << parameters.env >>
    steps:
      - attach_workspace:
          at: ~/<< pipeline.parameters.workingdir >>/<< parameters.env >>
      - run:
          command: |
            ls
            pwd
workflows:
  my-workflow:
    jobs:
      - build:
          matrix:
            parameters:
              env: ["dev", "test"]
      - build:
          type: approval
          name: approve-<< matrix.env >>
          matrix:
            parameters:
              env: ["dev", "test"]
          requires:
            - build-<< matrix.env >>
      - deploy:
          name: apply
          requires:
            - approve-dev
