version: 2.1

parameters:
  workingdir:
    type: string
    default: "~/infra/dev"

base_image: &base_image hashicorp/terraform:0.12.29

default_config: &default_config
  docker:
    - image: *base_image

commands:
  print:
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>
  greeting:
    parameters:
      env:
        type: string
        default: "dev"
    steps:
      - run: export ENV=<< parameters.env >>

jobs:
  cat-file:
    <<: *default_config
    parameters:
      env:
        type: string
        default: dev
    environment:
      ENV: << parameters.env >>
    steps:
      - run: touch << parameters.file >>
      - print:
          message: Printing << parameters.file >>
      - run: cat << parameters.file >>
      - run: echo $ENV
      - run: env

workflows:
  my-workflow:
    jobs:
      - cat-file:
          env: test
