version: 2.1

parameters:
  workingdir:
    type: string
    default: "~/infra/dev"

# commands:
#   greeting:
#     parameters:
#       env:
#         type: string
#         default: "dev"
#     steps:
#       - run: export ENV=dev
#       - run: echo $ENV

base_image: &base_image hashicorp/terraform:0.12.29

default_config: &default_config
  docker:
    - image: *base_image

commands:
  print:
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>

jobs:
  cat-file:
    <<: *default_config
    parameters:
      file:
        type: string
    steps:
      - print:
          message: Printing << parameters.file >>
      - run: cat << parameters.file >>

workflows:
  my-workflow:
    jobs:
      - cat-file:
          file: test.txt
