version: 2.1

executors:
  default-executor:
    docker:
      - image: hashicorp/terraform:0.12.29

parameters:
  workingdir:
    type: string
    default: "~/infra/dev"

commands:
  print:
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>
  greeting:
    parameters:
      env:
        type: string
        default: "dev"
    steps:
      - run: export ENV=<< parameters.env >>

jobs:
  build:
    executor: default-executor
    parameters:
      env:
        type: string
        default: dev
    environment:
      ENV: << parameters.env >>
    steps:
      - run: echo $ENV
  deploy:
    executor: default-executor
    parameters:
      env:
        type: string
        default: dev
    environment:
      ENV: << parameters.env >>
    steps:
      - run:
          command: |
            ls 
            circleci-agent step halt
workflows:
  my-workflow:
    jobs:
      - build:
          matrix:
            parameters:
              env: ["dev", "test"]
      - build:
          type: approval
          name: approve-<< matrix.env >>
          matrix:
            parameters:
              env: ["dev", "test"]
          requires:
            - build-<< matrix.env >>
      - deploy:
          name: apply
          requires:
            - approve-dev
