version: 2.1

executors:
  default-executor:
    docker:
      - image: hashicorp/terraform:0.12.29

parameters:
  workingdir:
    type: string
    default: "~/infra/dev"

commands:
  print:
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>
  greeting:
    parameters:
      env:
        type: string
        default: "dev"
    steps:
      - run: export ENV=<< parameters.env >>

jobs:
  cat-file:
    executor: default-executor
    parameters:
      env:
        type: string
        default: dev
    environment:
      ENV: << parameters.env >>
    steps:
      - run: echo $ENV

workflows:
  my-workflow:
    jobs:
      - cat-file:
          name: build-test
          env: test
      - cat-file:
          name: build-dev
          env: dev
      - approve:
          type: approval
          name: apply-test
          requires:
            - build-test
      - approve:
          type: approval
          name: apply-dev
          requires:
            - build-dev
      - cat-file:
          name: apply-test
          env: dev
          requires:
            - apply-test
      - cat-file:
          name: apply-dev
          env: dev
          requires:
            - apply-dev
