server:
  port: :8080
db:
  host: localhost
  port: 5432
  user: circleci-demo-go
  dbname: circle_test
  password:
  maxcons: 10
  maxidlecons: 2
jwt:
  key: test123
firebase:
  credentials: /Users/xucheng/fir-learn-f939d-firebase-adminsdk-hdw4p-8484139d16.json
nihaopay:
  api: https://apitest.nihaopay.com/v1.2
  token: Bearer 6c4dc4828474fa73c5f438a9eb2fbf3092e441d9f2ea5fbcf93b51a232ddc249
  ipn_url: https://1c5ef59140ad.ngrok.io/v1/pay/callback
  callback_url: http://localhost:8080/v1/pay
